# Generated by Django 3.2.3 on 2021-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_challenge_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_over_email_sent",
            field=models.CharField(
                choices=[("passed", "Passed"), ("failed", "Failed")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
