# Generated by Django 2.0.13 on 2019-04-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deploy_private_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deploy_public_key",
            field=models.TextField(blank=True),
        ),
    ]
