# Generated by Django 3.2.3 on 2021-05-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_user_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userwhitelist",
            name="student",
        ),
        migrations.AddField(
            model_name="userwhitelist",
            name="is_instructor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userwhitelist",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("other", "Other/Prefer not to say"),
                ],
                max_length=25,
            ),
        ),
    ]
