# Generated by Django 3.2.3 on 2021-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20210531_2258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="applying_for_scholarship",
            field=models.BooleanField(default=False),
        ),
    ]
