# Generated by Django 3.2.3 on 2021-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_user_applying_for_scholarship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="profession",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
