# Generated by Django 4.2.14 on 2024-09-15 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_user_academy_type_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="logo",
        ),
    ]
