# Generated by Django 4.2.14 on 2026-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admissions_mode",
            field=models.CharField(
                choices=[("exam", "Exam"), ("no_exam", "No exam")],
                default="exam",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_completed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
