# Generated by Django 4.2.14 on 2026-10-03 11:12

from django.db import migrations, models


def initialize_student_reset_retention(apps, schema_editor):
    User = apps.get_model("users", "User")
    student_only = models.Q(
        is_student=True,
        is_staff=False,
        is_superuser=False,
        is_instructor=False,
    )
    User.objects.filter(student_only).update(
        retain_student_account_on_next_edition_reset=False
    )
    User.objects.exclude(student_only).update(
        retain_student_account_on_next_edition_reset=None
    )


def clear_student_reset_retention(apps, schema_editor):
    apps.get_model("users", "User").objects.update(
        retain_student_account_on_next_edition_reset=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_user_admissions_mode_user_registration_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="retain_student_account_on_next_edition_reset",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Student-only accounts: select to preserve the complete user account and student status during the next edition reset. Academic and admissions activity is still deleted. After a successful reset, this setting returns to unselected and must be authorized again for a later reset. This does not apply to staff, superusers, instructors, or other non-student accounts.",
                null=True,
                verbose_name="Retain student account on next edition reset",
            ),
        ),
        migrations.RunPython(
            initialize_student_reset_retention,
            clear_student_reset_retention,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("is_instructor", False),
                        ("is_staff", False),
                        ("is_student", True),
                        ("is_superuser", False),
                        ("retain_student_account_on_next_edition_reset__isnull", False),
                    ),
                    models.Q(
                        models.Q(
                            ("is_instructor", False),
                            ("is_staff", False),
                            ("is_student", True),
                            ("is_superuser", False),
                            _negated=True,
                        ),
                        ("retain_student_account_on_next_edition_reset__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="users_student_reset_retention_matches_role",
            ),
        ),
    ]
