# Generated by Django 3.2.3 on 2021-05-27 18:19

import django.db.models.deletion
from django.db import migrations, models

import portal.applications.models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0007_auto_20210523_1559"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="")),
                ("max_score", models.FloatField(default=20)),
                ("pass_score", models.FloatField(default=16)),
            ],
        ),
        migrations.RemoveField(
            model_name="submission",
            name="feedback_location",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="file_location",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="submission_type",
        ),
        migrations.AddField(
            model_name="submission",
            name="feedback",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.applications.models.feedback_path,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.applications.models.notebook_path,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="challenge",
            field=models.ForeignKey(
                default="slu00",
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.challenge",
            ),
            preserve_default=False,
        ),
    ]
