# Generated by Django 3.2.3 on 2021-06-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0009_auto_20210531_2258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
