# Generated by Django 3.2.3 on 2021-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0010_alter_challenge_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="file",
            field=models.FileField(blank=True, default="", upload_to=""),
            preserve_default=False,
        ),
    ]
