# Generated by Django 3.2.4 on 2021-06-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0014_alter_submission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
