# Generated by Django 3.2.4 on 2023-02-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0015_alter_submission_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="coding_test_started_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
