# Generated by Maria on 2025-07-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0016_alter_application_coding_test_started_at.py"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="coding_test_downloaded",
            field=models.IntegerField()
        ),
        migrations.AddField(
            model_name="application",
            name="slu01_downloaded",
            field=models.IntegerField()
        ),
        migrations.AddField(
            model_name="application",
            name="slu02_downloaded",
            field=models.IntegerField()
        ),
        migrations.AddField(
            model_name="application",
            name="slu03_downloaded",
            field=models.IntegerField()
        ),
    ]
