default_language_version:
  python: python3.10
exclude: .*migrations\/.*|.git

ci:
  autofix_prs: false
  
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
    - id: ruff
      args: [--config=pyproject.toml]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
    - id: black
      args: [--config=pyproject.toml]
