version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --only docs
    pre_build:
      - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/source $READTHEDOCS_OUTPUT/linkcheck

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - htmlzip
  - epub
  - pdf
