version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 5678:5678
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver_plus 0.0.0.0:8000

  scheduler:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    command: ./manage.py run-scheduler

  postgres:
    image: postgres:14.5
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=portal
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal
    ports:
      - '5432:5432'
    expose:
      - 5432
    container_name: postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

networks:
  default:
    external: true
    name: portal
