# Generated by Django 2.2.1 on 2019-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userwhitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwhitelist',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
