# Generated by Django 2.2.3 on 2019-11-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
