apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldsa-portal.fullname" . }}
  labels:
    app: {{ include "ldsa-portal.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "ldsa-portal.name" . }}
