# Generated by Django 2.2.1 on 2019-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_auto_20190427_1443"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="open",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="grade",
            name="status",
            field=models.CharField(
                choices=[
                    ("never-submitted", "Never Submitted"),
                    ("grading", "Grading..."),
                    ("failed", "Grading failed!"),
                    ("out-of-date", "Out-of-date, resubmit"),
                    ("graded", "Graded"),
                ],
                default="never-submitted",
                max_length=1024,
            ),
        ),
    ]
