# Generated by Django 2.2.1 on 2019-07-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0004_auto_20190703_1710"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="started",
            field=models.BooleanField(default=False),
        ),
    ]
