# Generated by Django 2.2.1 on 2019-07-14 09:28

from django.db import migrations, models
import portal.hackathons.models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_auto_20190714_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to=portal.hackathons.models.random_path),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to=portal.hackathons.models.random_path),
        ),
    ]
