# Generated by Django 2.2.3 on 2019-07-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0008_auto_20190714_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hackathon',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hackathons.Hackathon'),
            preserve_default=False,
        ),
    ]
