# Generated by Django 3.0.6 on 2020-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0010_auto_20200517_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='team',
            name='remote',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('marking_presences', 'Marking Presences'), ('generating_teams', 'Generating Teams'), ('ready', 'Ready'), ('submissions_open', 'Submissions Open'), ('submissions_closed', 'Submissions Closed'), ('complete', 'Complete')], default='closed', max_length=255),
        ),
    ]
