version: 2

fast-checkout: &fast-checkout
  attach_workspace:
    at: /tmp/workspace

jobs:
  persist-checkout:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: Store image tag
          command: |
            echo "IMAGE_TAG=$(echo `git log -n1 --format="%h"`)" >> $HOME/env
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
            - env

  test-snyk:
    docker:
      - image: snyk/snyk-cli:python-3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        environment:
          SNYK_TOKEN: TODO
          MONITOR: "true"
          PROJECT_FOLDER: /tmp/workspace/project
    steps:
      - *fast-checkout
      - run:
          name: Run snyk
          command: |
            snyk test --org=$SNYK_ORG_ID

  test-prospector:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - *fast-checkout
      - run:
          name: Run prospector
          command: |
            cd /tmp/workspace/project
            pip3 install prospector[with_everything]
            which prospector
            prospector
  build:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - *fast-checkout
      - setup_remote_docker
      - run:
          name: Build and push django image
          command: |
            source /tmp/workspace/env
            docker build -f docker/local/django/Dockerfile -t django:$IMAGE_TAG .
            docker save -o /tmp/workspace/image/django.tar oxpecker-api:$IMAGE_TAG
      - persist_to_workspace:
          root: /root
          paths:
            - image/django.tar

  push:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace/image
      - run:
          name: Build and push django image
          command: |
            source /tmp/workspace/env
            docker load -i /tmp/workspace/image/django.tar
            docker push ldssa/django:$IMAGE_TAG

  deploy:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - run:
          name: Deploy
          command: |
            sentry-cli releases new --finalize -p backend oxpecker-api:$CI_COMMIT_SHORT_SHA
            sentry-cli releases set-commits --auto oxpecker-api:$CI_COMMIT_SHORT_SHA

workflows:
  version: 2

  workflow:
    jobs:
      - persist-checkout:
          context: 
            - Common Env
      - test-snyk:
          context: 
            - Common Env
          requires:
            - persist-checkout
      - test-prospector:
          context: 
            - Common Env
          requires:
            - persist-checkout
      - approval:
          context: 
            - Common Env
          requires:
            - test-snyk
            - test-prospector
      - build:
          context: 
            - Common Env
          requires:
            - approval
      - push:
          context: 
            - Common Env
          requires:
            - build
      - deploy:
          context: 
            - Common Env
          requires:
            - approval