version: 2

fast-checkout: &fast-checkout
  attach_workspace:
    at: /tmp/workspace

jobs:
  persist-checkout:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: Store image tag
          command: |
            echo "IMAGE_TAG=$(echo `git log -n1 --format="%h"`)" >> $HOME/env
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
            - env

  build:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - *fast-checkout
      - setup_remote_docker
      - run:
          name: Build django image
          command: |
            set -ex
            cd /tmp/workspace/project
            source /tmp/workspace/env
            docker build -t ldssa/django:$IMAGE_TAG .
            mkdir -p /tmp/workspace/image
            docker save -o /tmp/workspace/image/django.tar ldssa/django:$IMAGE_TAG
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - image/django.tar
  push:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Push django image
          command: |
            source /tmp/workspace/env
            docker load -i /tmp/workspace/image/django.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ldssa/django:$IMAGE_TAG

workflows:
  version: 2

  workflow:
    jobs:
      - persist-checkout:
          context: 
            - Common Env
      - build:
          context: 
            - Common Env
          requires:
            - persist-checkout
      - approval:
          type: approval
          context: 
            - Common Env
          requires:
            - build
      - push:
          context: 
            - Common Env
          requires:
            - approval
