# Generated by Django 2.2.1 on 2019-06-15 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_auto_20190610_1757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
