# Generated by Django 2.2.3 on 2020-05-17 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0006_auto_20190622_0955"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="grade",
            name="updated",
        ),
    ]
