# Generated by Django 4.2.14 on 2024-10-01 18:09

from django.db import migrations, models

import portal.academy.models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0010_grade_on_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="notebook",
            field=models.FileField(
                blank=True, null=True, upload_to=portal.academy.models.notebook_path
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
