# Generated by Django 4.2.14 on 2026-09-24 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0011_alter_grade_notebook_alter_grade_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="required_for_certificate",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
