# Generated by Django 4.2.14 on 2026-09-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0013_optional_bootcamp_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="available_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
