# Generated by Django 4.2.14 on 2026-09-24 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academy", "0014_unit_available_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="deadline_override_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="deadline_override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deadline_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="deadline_override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="deadline_valid_override",
            field=models.BooleanField(
                blank=True,
                help_text="Unknown uses the recorded on-time result; Yes accepts the deadline exception; No invalidates it.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GradeDeadlineDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_value", models.BooleanField(null=True)),
                ("new_value", models.BooleanField(null=True)),
                ("reason", models.TextField()),
                ("actor_username", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadline_decisions",
                        to="academy.grade",
                    ),
                ),
            ],
        ),
    ]
