# Generated by Django 2.2.3 on 2019-11-18 21:34

from django.db import migrations, models
import portal.hackathons.models


class Migration(migrations.Migration):

    dependencies = [
        ("capstone", "0003_auto_20191115_2201"),
    ]

    operations = [
        migrations.AddField(
            model_name="capstone",
            name="scoring",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.hackathons.models.random_path,
            ),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="outcome",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="duedatapoint",
            name="response_exception",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="duedatapoint",
            name="response_traceback",
            field=models.TextField(blank=True),
        ),
    ]
