# Generated by Django 3.2.4 on 2022-01-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_auto_20210531_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duedatapoint',
            name='state',
            field=models.CharField(choices=[('queued', 'queued'), ('success', 'success'), ('fail', 'fail')], default='queued', max_length=64),
        ),
        migrations.AddIndex(
            model_name='duedatapoint',
            index=models.Index(fields=['due', 'state'], name='capstone_du_due_1cafd1_idx'),
        ),
    ]
