# Generated by Django 4.2.5 on 2024-05-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0012_auto_20220115_2032"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capstone",
            name="report_1_final_open",
        ),
        migrations.RemoveField(
            model_name="capstone",
            name="report_1_provisory_open",
        ),
        migrations.RemoveField(
            model_name="capstone",
            name="report_2_final_open",
        ),
        migrations.RemoveField(
            model_name="capstone",
            name="report_2_provisory_open",
        ),
        migrations.AddField(
            model_name="capstone",
            name="proposal_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="capstone",
            name="report_final_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="capstone",
            name="report_provisory_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="type",
            field=models.CharField(
                choices=[
                    ("proposal", "Proposal"),
                    ("report_provisory", "Report Provisory"),
                    ("report_final", "Report Final"),
                ],
                max_length=32,
            ),
        ),
    ]
