# Generated by Django 3.2.3 on 2021-05-27 18:19

from django.db import migrations, models
import portal.selection.models


class Migration(migrations.Migration):

    dependencies = [
        ("selection", "0004_auto_20210523_1559"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selectiondocument",
            name="file_location",
        ),
        migrations.AddField(
            model_name="selectiondocument",
            name="doc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.selection.models.get_path,
            ),
        ),
    ]
