# Generated by Django 2.2.1 on 2019-07-01 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="attendance_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
