# Generated by Django 2.2.1 on 2019-07-02 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0002_auto_20190701_2054"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="max_team_size",
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="max_teams",
            field=models.IntegerField(default=13),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="team_size",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="teams_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="hackathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="hackathons.Hackathon",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="hackathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="hackathons.Hackathon",
            ),
        ),
    ]
