# Generated by Django 2.2.1 on 2019-07-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0003_auto_20190702_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
