# Generated by Django 3.1.7 on 2021-02-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0011_auto_20200727_1738"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="max_submissions",
            field=models.IntegerField(default=5),
        ),
    ]
