# Generated by Django 3.2.3 on 2021-05-31 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0013_auto_20210523_1559"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="student",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="students",
            new_name="users",
        ),
    ]
