replicaCount: 1

strategy:
  rollingUpdate:
    maxSurge: 2
    maxUnavailable: 0

environment: production

kubeconfigConfigMapName: kubeconfig-configmap
awsConfigMapName: aws-configmap

image:
  repository: ldssa/django
  tag: UNSET

startScript: /app/bin/start_prod.sh

env:
  - name: BASE_URL
    key: BASE_URL
    configMapName: django-configmap
  - name: STUDENT_REPO_NAME
    key: STUDENT_REPO_NAME
    configMapName: django-configmap
  - name: GRADING_USERNAME
    key: GRADING_USERNAME
    configMapName: django-configmap
  - name: DJANGO_ALLOWED_HOSTS
    key: DJANGO_ALLOWED_HOSTS
    configMapName: django-configmap
  - name: DJANGO_SETTINGS_MODULE
    key: DJANGO_SETTINGS_MODULE
    configMapName: django-configmap
  - name: DJANGO_CACHE_BACKEND
    key: DJANGO_CACHE_BACKEND
    configMapName: django-configmap
  - name: REDIS_URL
    key: REDIS_URL
    configMapName: django-configmap
  - name: DJANGO_SECURE_SSL_REDIRECT
    key: DJANGO_SECURE_SSL_REDIRECT
    configMapName: django-configmap
  - name: DJANGO_EMAIL_BACKEND
    key: DJANGO_EMAIL_BACKEND
    configMapName: django-configmap
  - name: DJANGO_DEFAULT_FROM_EMAIL
    key: DJANGO_DEFAULT_FROM_EMAIL
    configMapName: django-configmap
  - name: DJANGO_STATICFILES_STORAGE
    key: DJANGO_STATICFILES_STORAGE
    configMapName: django-configmap
  - name: DJANGO_AWS_STORAGE_BUCKET_NAME
    key: DJANGO_AWS_STORAGE_BUCKET_NAME
    configMapName: django-configmap
  - name: DJANGO_AWS_S3_REGION_NAME
    key: DJANGO_AWS_S3_REGION_NAME
    configMapName: django-configmap
  - name: POSTGRES_DB
    key: POSTGRES_DB
    configMapName: django-configmap
  - name: POSTGRES_PORT
    key: POSTGRES_PORT
    configMapName: django-configmap
  - name: POSTGRES_USER
    key: POSTGRES_USER
    configMapName: django-configmap
  - name: SENTRY_DSN
    key: SENTRY_DSN
    configMapName: django-configmap
  - name: COMPRESS_ENABLED
    key: COMPRESS_ENABLED
    configMapName: django-configmap
  - name: COMPRESS_STORAGE
    key: COMPRESS_STORAGE
    configMapName: django-configmap
  - name: WEB_CONCURRENCY
    key: WEB_CONCURRENCY
    configMapName: django-configmap
  - name: SLACK_WORKSPACE
    key: SLACK_WORKSPACE
    configMapName: django-configmap

ingress:
  annotations:
    certManagerIssuer: letsencrypt
    proxyBodySize: "10m"
  className: nginx
  host: UNSET
  secretName: portal-crt

service:
  port: 5000
  type: ClusterIP

letsencrypt:
  name: letsencrypt
  server: https://acme-v02.api.letsencrypt.org/directory
  email: gustavo.fonseca@lisbondatascience.org
  privateKeySecretName: letsencrypt
  ingressClass: nginx

serviceAccount:
  create: false

autoscaling:
  enabled: false

postgres:
  db: UNSET
