# Generated by Django 4.2.14 on 2026-10-01 11:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingJob",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("backend", models.CharField(max_length=12)),
                ("remote_seen", models.BooleanField(default=False)),
                ("status", models.CharField(default="launching", max_length=16)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PortalState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("phase", models.CharField(default="open", max_length=20)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("ready_release", models.CharField(blank=True, max_length=100)),
                ("worker_seen", models.DateTimeField(null=True)),
                ("worker_release", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EditionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(default="reset", max_length=12)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("actor_username", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("finished", models.DateTimeField(null=True)),
                ("release", models.CharField(max_length=100)),
                ("database", models.CharField(max_length=255)),
                ("plan", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                ("backup_first", models.BooleanField(default=True)),
                ("backup_name", models.CharField(blank=True, max_length=255)),
                ("backup_sha256", models.CharField(blank=True, max_length=64)),
                ("backup_bytes", models.BigIntegerField(default=0)),
                ("backup_deleted", models.BooleanField(default=False)),
                ("result", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Edition reset",
                "ordering": ["-created"],
            },
        ),
    ]
