# Generated by Django 2.2.3 on 2019-11-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="duedatapoint",
            name="url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
