# Generated by Django 3.2.4 on 2022-01-09 12:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import portal.capstone.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("capstone", "0008_auto_20210531_2258"),
    ]

    operations = [
        migrations.AddField(
            model_name="capstone",
            name="report_1_final_due_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="capstone",
            name="report_1_provisory_due_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="capstone",
            name="report_2_final_due_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="capstone",
            name="report_2_provisory_due_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("report_1_provisory", "Report 1 Provisory"),
                            ("report_1_final", "Report 1 Final"),
                            ("report_2_provisory", "Report 2 Provisory"),
                            ("report_2_final", "Report 2 Final"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=portal.capstone.models.report_path,
                    ),
                ),
                ("delivery", models.DateTimeField(auto_now=True)),
                (
                    "capstone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capstone.capstone",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
