# Generated by Django 3.2.4 on 2022-01-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_auto_20220109_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='delivery',
            new_name='submited_at',
        ),
    ]
