version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: .
    depends_on:
      - postgres
      - mailhog
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    command: /app/bin/start_dev.sh

  scheduler:
    build:
      context: .
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    command: ./bin/start_scheduler.sh

  postgres:
    image: postgres:14.5
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=portal
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal
    ports:
      - '5432:5432'
    expose:
      - 5432
    container_name: postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

networks:
  default:
    external: true
    name: portal
